### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vuejs.org#86]
- [x] yyx990803/vue#980 Objects are pre-processed to Arrays in `v-repeat` filters
- [ ] yyx990803/vue#988 Difference between internal and user watchers
- [ ] vuejs/Discussion#213 Best practices for tearing down manual timers/listeners
- [x] yyx990803/vue#1061 Add custom filter example for `<select>` dynamic options
- [ ] tips on integration with 3rd party libs: wrap them with custom directives

**Comment by Codebryo** [comment]
I found a nice way of integrating Vue with CoffeeScript Classes. Is this something that would fit the page?

**Comment by yyx990803** [comment]
@Codebryo Hmm maybe not in the official docs, but I'm thinking of something like a "Vue.js cookbook" where everyone can contribute to.

**Comment by imaia** [comment]
I would like to see that, @codebryo

**Comment by mitar** [comment]
> I found a nice way of integrating Vue with CoffeeScript Classes. Is this something that would fit the page?

Me too.

**Comment by chrisvfritz** [comment]
Closing this and splitting out the remaining items into individual issues, so that they're more visible and can be individually tracked.
